setwd('/Users/cgarvey/Documents/NBA/main/')
library(plyr)
library(ggplot2)
library(scatterplot3d)

boxscores = read.csv("stats/boxscores.csv")
player_per_game = read.csv("stats/player_per_game.csv")
player_per_game_by_season = read.csv("stats/player_per_game_by_season.csv")
team_per_game = read.csv("stats/team_per_game.csv")
team_per_game_by_season = read.csv("stats/team_per_game_by_season.csv")
home_v_away_per_game = read.csv("stats/home_v_away_per_game.csv")
home_v_away_per_game_by_season = read.csv("stats/home_v_away_per_game_by_season.csv")
player_info = read.csv("stats/player_info.csv")
player_salaries = read.csv("stats/player_salaries.csv")
player_salaries_by_season = read.csv("stats/player_salaries_by_season.csv")
team_salaries = read.csv("stats/team_salaries.csv")
team_salaries_by_season = read.csv("stats/team_salaries_by_season.csv")

head(boxscores, 10)
head(player_per_game, 10)
head(player_per_game_by_season, 10)
head(team_per_game, 10)
head(team_per_game_by_season, 10)
head(home_v_away_per_game, 10)
head(home_v_away_per_game_by_season, 10)
head(player_info, 10)
head(player_salaries, 10)
head(player_salaries_by_season, 10)
head(team_salaries, 10)
head(team_salaries_by_season, 10)
